"use client";
import "./globals.css";
import { AuthContextProvider } from "./context/AuthContext";
import { ThemeProvider } from "styled-components";
import theme from "./theme";
import { CssBaseline } from "@mui/material";
import { DrawerAppBar } from "./components/DrawerAppBar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <AuthContextProvider>
            {/* <Navbar />
          {children} */}
            <DrawerAppBar children={children} />
            {/* <Component {...children} /> */}
            {/* {children} */}
          </AuthContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
